datadog:
  apiKeyExistingSecret: datadog-secret  
  appKeyExistingSecret: datadog-secret  
  site: datadoghq.eu  
  admissionController:
    enabled: true 
agents:
  apm:
    enabled: true  
    socketEnabled: true 
    portEnabled: true  
    hostSocketPath: /var/run/datadog/  
    socketPath: /var/run/datadog/apm.socket 
  processAgent:
    enabled: true 
  volumes:
    - name: logdatadog
      emptyDir: {}  
  volumeMounts:
    - name: logdatadog
      mountPath: /var/log/datadog
  annotations:
    ad.datadoghq.eu/nodejs-app.logs: |
      [
        {
          "source": "nodejs",
          "service": "nodejs-app"
        }
      ]   
  env:
    - name: DD_AGENT_HOST
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP  
    - name: DD_ENV
      value: "production"  
    - name: DD_SERVICE
      value: "nodejs-app"  
    - name: DD_VERSION
      value: "1.0.0"  
containers:
  - name: nodejs-app
    image: ##nodejs-repo  
    ports:
      - containerPort: 3001 
    env:
      - name: DD_AGENT_HOST
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP  
      - name: DD_ENV
        value: "production"
      - name: DD_SERVICE
        value: "nodejs-app"
      - name: DD_VERSION
        value: "1.0.0"
